export const data = {
  "modules": [{
    "name": "app/account/account.module",
    "modulePath": "src/app/account",
    "moduleFullPath": "src/app/account/account.module.ts",
    "moduleName": "account.module.ts"
  }, {
    "name": "app/activate/activate.module",
    "modulePath": "src/app/activate",
    "moduleFullPath": "src/app/activate/activate.module.ts",
    "moduleName": "activate.module.ts"
  }, {
    "name": "app/admin/admin.module",
    "modulePath": "src/app/admin",
    "moduleFullPath": "src/app/admin/admin.module.ts",
    "moduleName": "admin.module.ts"
  }, {
    "name": "app/admin/modules/accounts/accounts.module",
    "modulePath": "src/app/admin/modules/accounts",
    "moduleFullPath": "src/app/admin/modules/accounts/accounts.module.ts",
    "moduleName": "accounts.module.ts"
  }, {
    "name": "app/admin/modules/accounts/modules/account/account.module",
    "modulePath": "src/app/admin/modules/accounts/modules/account",
    "moduleFullPath": "src/app/admin/modules/accounts/modules/account/account.module.ts",
    "moduleName": "account.module.ts"
  }, {
    "name": "app/admin/modules/accounts/modules/api-keys/api-keys.module",
    "modulePath": "src/app/admin/modules/accounts/modules/api-keys",
    "moduleFullPath": "src/app/admin/modules/accounts/modules/api-keys/api-keys.module.ts",
    "moduleName": "api-keys.module.ts"
  }, {
    "name": "app/admin/modules/content/content.module",
    "modulePath": "src/app/admin/modules/content",
    "moduleFullPath": "src/app/admin/modules/content/content.module.ts",
    "moduleName": "content.module.ts"
  }, {
    "name": "app/admin/modules/docs/docs.module",
    "modulePath": "src/app/admin/modules/docs",
    "moduleFullPath": "src/app/admin/modules/docs/docs.module.ts",
    "moduleName": "docs.module.ts"
  }, {
    "name": "app/admin/modules/images/images.module",
    "modulePath": "src/app/admin/modules/images",
    "moduleFullPath": "src/app/admin/modules/images/images.module.ts",
    "moduleName": "images.module.ts"
  }, {
    "name": "app/admin/modules/messages/messages.module",
    "modulePath": "src/app/admin/modules/messages",
    "moduleFullPath": "src/app/admin/modules/messages/messages.module.ts",
    "moduleName": "messages.module.ts"
  }, {
    "name": "app/admin/modules/plans/plans.module",
    "modulePath": "src/app/admin/modules/plans",
    "moduleFullPath": "src/app/admin/modules/plans/plans.module.ts",
    "moduleName": "plans.module.ts"
  }, {
    "name": "app/admin/modules/projects/projects.module",
    "modulePath": "src/app/admin/modules/projects",
    "moduleFullPath": "src/app/admin/modules/projects/projects.module.ts",
    "moduleName": "projects.module.ts"
  }, {
    "name": "app/admin/modules/tasks/tasks.module",
    "modulePath": "src/app/admin/modules/tasks",
    "moduleFullPath": "src/app/admin/modules/tasks/tasks.module.ts",
    "moduleName": "tasks.module.ts"
  }, {
    "name": "app/admin/modules/workspaces/workspaces.module",
    "modulePath": "src/app/admin/modules/workspaces",
    "moduleFullPath": "src/app/admin/modules/workspaces/workspaces.module.ts",
    "moduleName": "workspaces.module.ts"
  }, {
    "name": "app/app.module",
    "modulePath": "src/app",
    "moduleFullPath": "src/app/app.module.ts",
    "moduleName": "app.module.ts"
  }, {
    "name": "app/common/common.module",
    "modulePath": "src/app/common",
    "moduleFullPath": "src/app/common/common.module.ts",
    "moduleName": "common.module.ts"
  }, {
    "name": "app/core/core.module",
    "modulePath": "src/app/core",
    "moduleFullPath": "src/app/core/core.module.ts",
    "moduleName": "core.module.ts"
  }, {
    "name": "app/data/data.module",
    "modulePath": "src/app/data",
    "moduleFullPath": "src/app/data/data.module.ts",
    "moduleName": "data.module.ts"
  }, {
    "name": "app/environment/environment.module",
    "modulePath": "src/app/environment",
    "moduleFullPath": "src/app/environment/environment.module.ts",
    "moduleName": "environment.module.ts"
  }, {
    "name": "app/environment/modules/create/create.module",
    "modulePath": "src/app/environment/modules/create",
    "moduleFullPath": "src/app/environment/modules/create/create.module.ts",
    "moduleName": "create.module.ts"
  }, {
    "name": "app/environment/modules/doc/doc.module",
    "modulePath": "src/app/environment/modules/doc",
    "moduleFullPath": "src/app/environment/modules/doc/doc.module.ts",
    "moduleName": "doc.module.ts"
  }, {
    "name": "app/environment/modules/images/images.module",
    "modulePath": "src/app/environment/modules/images",
    "moduleFullPath": "src/app/environment/modules/images/images.module.ts",
    "moduleName": "images.module.ts"
  }, {
    "name": "app/environment/modules/members/members.module",
    "modulePath": "src/app/environment/modules/members",
    "moduleFullPath": "src/app/environment/modules/members/members.module.ts",
    "moduleName": "members.module.ts"
  }, {
    "name": "app/environment/modules/members/modules/integrations/integrations.module",
    "modulePath": "src/app/environment/modules/members/modules/integrations",
    "moduleFullPath": "src/app/environment/modules/members/modules/integrations/integrations.module.ts",
    "moduleName": "integrations.module.ts"
  }, {
    "name": "app/environment/modules/plans/plans.module",
    "modulePath": "src/app/environment/modules/plans",
    "moduleFullPath": "src/app/environment/modules/plans/plans.module.ts",
    "moduleName": "plans.module.ts"
  }, {
    "name": "app/environment/modules/projects/projects.module",
    "modulePath": "src/app/environment/modules/projects",
    "moduleFullPath": "src/app/environment/modules/projects/projects.module.ts",
    "moduleName": "projects.module.ts"
  }, {
    "name": "app/environment/modules/settings/settings.module",
    "modulePath": "src/app/environment/modules/settings",
    "moduleFullPath": "src/app/environment/modules/settings/settings.module.ts",
    "moduleName": "settings.module.ts"
  }, {
    "name": "app/environment/modules/task/task.module",
    "modulePath": "src/app/environment/modules/task",
    "moduleFullPath": "src/app/environment/modules/task/task.module.ts",
    "moduleName": "task.module.ts"
  }, {
    "name": "app/invite/invite.module",
    "modulePath": "src/app/invite",
    "moduleFullPath": "src/app/invite/invite.module.ts",
    "moduleName": "invite.module.ts"
  }, {
    "name": "app/kb/kb.module",
    "modulePath": "src/app/kb",
    "moduleFullPath": "src/app/kb/kb.module.ts",
    "moduleName": "kb.module.ts"
  }, {
    "name": "app/lab/lab.module",
    "modulePath": "src/app/lab",
    "moduleFullPath": "src/app/lab/lab.module.ts",
    "moduleName": "lab.module.ts"
  }, {
    "name": "app/lab/modules/event/event.module",
    "modulePath": "src/app/lab/modules/event",
    "moduleFullPath": "src/app/lab/modules/event/event.module.ts",
    "moduleName": "event.module.ts"
  }, {
    "name": "app/password/password.module",
    "modulePath": "src/app/password",
    "moduleFullPath": "src/app/password/password.module.ts",
    "moduleName": "password.module.ts"
  }, {
    "name": "app/plan/plan.module",
    "modulePath": "src/app/plan",
    "moduleFullPath": "src/app/plan/plan.module.ts",
    "moduleName": "plan.module.ts"
  }, {
    "name": "app/projects/modules/plans/plans.module",
    "modulePath": "src/app/projects/modules/plans",
    "moduleFullPath": "src/app/projects/modules/plans/plans.module.ts",
    "moduleName": "plans.module.ts"
  }, {
    "name": "app/projects/modules/project/modules/board/board.module",
    "modulePath": "src/app/projects/modules/project/modules/board",
    "moduleFullPath": "src/app/projects/modules/project/modules/board/board.module.ts",
    "moduleName": "board.module.ts"
  }, {
    "name": "app/projects/modules/project/modules/settings/settings.module",
    "modulePath": "src/app/projects/modules/project/modules/settings",
    "moduleFullPath": "src/app/projects/modules/project/modules/settings/settings.module.ts",
    "moduleName": "settings.module.ts"
  }, {
    "name": "app/projects/modules/project/project.module",
    "modulePath": "src/app/projects/modules/project",
    "moduleFullPath": "src/app/projects/modules/project/project.module.ts",
    "moduleName": "project.module.ts"
  }, {
    "name": "app/projects/projects.module",
    "modulePath": "src/app/projects",
    "moduleFullPath": "src/app/projects/projects.module.ts",
    "moduleName": "projects.module.ts"
  }, {
    "name": "app/reports/reports.module",
    "modulePath": "src/app/reports",
    "moduleFullPath": "src/app/reports/reports.module.ts",
    "moduleName": "reports.module.ts"
  }, {
    "name": "app/scenario/scenario.module",
    "modulePath": "src/app/scenario",
    "moduleFullPath": "src/app/scenario/scenario.module.ts",
    "moduleName": "scenario.module.ts"
  }, {
    "name": "app/signin/signin.module",
    "modulePath": "src/app/signin",
    "moduleFullPath": "src/app/signin/signin.module.ts",
    "moduleName": "signin.module.ts"
  }, {
    "name": "app/signup/signup.module",
    "modulePath": "src/app/signup",
    "moduleFullPath": "src/app/signup/signup.module.ts",
    "moduleName": "signup.module.ts"
  }, {
    "name": "app/system/modules/logs/logs.module",
    "modulePath": "src/app/system/modules/logs",
    "moduleFullPath": "src/app/system/modules/logs/logs.module.ts",
    "moduleName": "logs.module.ts"
  }, {
    "name": "app/system/modules/object/object.module",
    "modulePath": "src/app/system/modules/object",
    "moduleFullPath": "src/app/system/modules/object/object.module.ts",
    "moduleName": "object.module.ts"
  }, {
    "name": "app/system/modules/processes/processes.module",
    "modulePath": "src/app/system/modules/processes",
    "moduleFullPath": "src/app/system/modules/processes/processes.module.ts",
    "moduleName": "processes.module.ts"
  }, {
    "name": "app/system/system.module",
    "modulePath": "src/app/system",
    "moduleFullPath": "src/app/system/system.module.ts",
    "moduleName": "system.module.ts"
  }, {
    "name": "app/time-entry/time-entry.module",
    "modulePath": "src/app/time-entry",
    "moduleFullPath": "src/app/time-entry/time-entry.module.ts",
    "moduleName": "time-entry.module.ts"
  }, {
    "name": "libs/account/assign-pill/assign-pill.module",
    "modulePath": "src/libs/account/assign-pill",
    "moduleFullPath": "src/libs/account/assign-pill/assign-pill.module.ts",
    "moduleName": "assign-pill.module.ts"
  }, {
    "name": "libs/account/component-task-select/component-task-select.module",
    "modulePath": "src/libs/account/component-task-select",
    "moduleFullPath": "src/libs/account/component-task-select/component-task-select.module.ts",
    "moduleName": "component-task-select.module.ts"
  }, {
    "name": "libs/account/form/account-form.module",
    "modulePath": "src/libs/account/form",
    "moduleFullPath": "src/libs/account/form/account-form.module.ts",
    "moduleName": "account-form.module.ts"
  }, {
    "name": "libs/account/plan-select/plan-select.module",
    "modulePath": "src/libs/account/plan-select",
    "moduleFullPath": "src/libs/account/plan-select/plan-select.module.ts",
    "moduleName": "plan-select.module.ts"
  }, {
    "name": "libs/account-autocomplete/account-autocomplete.module",
    "modulePath": "src/libs/account-autocomplete",
    "moduleFullPath": "src/libs/account-autocomplete/account-autocomplete.module.ts",
    "moduleName": "account-autocomplete.module.ts"
  }, {
    "name": "libs/account-create-dialog/account-create-dialog.module",
    "modulePath": "src/libs/account-create-dialog",
    "moduleFullPath": "src/libs/account-create-dialog/account-create-dialog.module.ts",
    "moduleName": "account-create-dialog.module.ts"
  }, {
    "name": "libs/account-date/account-date.module",
    "modulePath": "src/libs/account-date",
    "moduleFullPath": "src/libs/account-date/account-date.module.ts",
    "moduleName": "account-date.module.ts"
  }, {
    "name": "libs/account-image/account-image.module",
    "modulePath": "src/libs/account-image",
    "moduleFullPath": "src/libs/account-image/account-image.module.ts",
    "moduleName": "account-image.module.ts"
  }, {
    "name": "libs/account-name/account-image.module",
    "modulePath": "src/libs/account-name",
    "moduleFullPath": "src/libs/account-name/account-image.module.ts",
    "moduleName": "account-image.module.ts"
  }, {
    "name": "libs/account-request-header/account-request-header.module",
    "modulePath": "src/libs/account-request-header",
    "moduleFullPath": "src/libs/account-request-header/account-request-header.module.ts",
    "moduleName": "account-request-header.module.ts"
  }, {
    "name": "libs/account-roles/account-roles.module",
    "modulePath": "src/libs/account-roles",
    "moduleFullPath": "src/libs/account-roles/account-roles.module.ts",
    "moduleName": "account-roles.module.ts"
  }, {
    "name": "libs/acl-roles/acl-roles.module",
    "modulePath": "src/libs/acl-roles",
    "moduleFullPath": "src/libs/acl-roles/acl-roles.module.ts",
    "moduleName": "acl-roles.module.ts"
  }, {
    "name": "libs/assign-account-select/assign-account-select.module",
    "modulePath": "src/libs/assign-account-select",
    "moduleFullPath": "src/libs/assign-account-select/assign-account-select.module.ts",
    "moduleName": "assign-account-select.module.ts"
  }, {
    "name": "libs/attributes-manage/attributes-manage.module",
    "modulePath": "src/libs/attributes-manage",
    "moduleFullPath": "src/libs/attributes-manage/attributes-manage.module.ts",
    "moduleName": "attributes-manage.module.ts"
  }, {
    "name": "libs/audit-activity/audit-activity.module",
    "modulePath": "src/libs/audit-activity",
    "moduleFullPath": "src/libs/audit-activity/audit-activity.module.ts",
    "moduleName": "audit-activity.module.ts"
  }, {
    "name": "libs/audit-list/audit-list.module",
    "modulePath": "src/libs/audit-list",
    "moduleFullPath": "src/libs/audit-list/audit-list.module.ts",
    "moduleName": "audit-list.module.ts"
  }, {
    "name": "libs/autofocus/autofocus.module",
    "modulePath": "src/libs/autofocus",
    "moduleFullPath": "src/libs/autofocus/autofocus.module.ts",
    "moduleName": "autofocus.module.ts"
  }, {
    "name": "libs/dialogs/role-edit/role-edit.module",
    "modulePath": "src/libs/dialogs/role-edit",
    "moduleFullPath": "src/libs/dialogs/role-edit/role-edit.module.ts",
    "moduleName": "role-edit.module.ts"
  }, {
    "name": "libs/dialogs/workspace-create/workspace-create-dialog.module",
    "modulePath": "src/libs/dialogs/workspace-create",
    "moduleFullPath": "src/libs/dialogs/workspace-create/workspace-create-dialog.module.ts",
    "moduleName": "workspace-create-dialog.module.ts"
  }, {
    "name": "libs/doc-type/doc-type.module",
    "modulePath": "src/libs/doc-type",
    "moduleFullPath": "src/libs/doc-type/doc-type.module.ts",
    "moduleName": "doc-type.module.ts"
  }, {
    "name": "libs/drawers/component-drawer/component-dawer.module",
    "modulePath": "src/libs/drawers/component-drawer",
    "moduleFullPath": "src/libs/drawers/component-drawer/component-dawer.module.ts",
    "moduleName": "component-dawer.module.ts"
  }, {
    "name": "libs/drawers/data-object-drawer/data-object-dawer.module",
    "modulePath": "src/libs/drawers/data-object-drawer",
    "moduleFullPath": "src/libs/drawers/data-object-drawer/data-object-dawer.module.ts",
    "moduleName": "data-object-dawer.module.ts"
  }, {
    "name": "libs/drawers/doc-drawer/doc-drawer.module",
    "modulePath": "src/libs/drawers/doc-drawer",
    "moduleFullPath": "src/libs/drawers/doc-drawer/doc-drawer.module.ts",
    "moduleName": "doc-drawer.module.ts"
  }, {
    "name": "libs/drawers/drawer/drawer.module",
    "modulePath": "src/libs/drawers/drawer",
    "moduleFullPath": "src/libs/drawers/drawer/drawer.module.ts",
    "moduleName": "drawer.module.ts"
  }, {
    "name": "libs/drawers/drawer/modules/side-drawer-header/side-drawer-header.module",
    "modulePath": "src/libs/drawers/drawer/modules/side-drawer-header",
    "moduleFullPath": "src/libs/drawers/drawer/modules/side-drawer-header/side-drawer-header.module.ts",
    "moduleName": "side-drawer-header.module.ts"
  }, {
    "name": "libs/drawers/image-drawer/image-drawer.module",
    "modulePath": "src/libs/drawers/image-drawer",
    "moduleFullPath": "src/libs/drawers/image-drawer/image-drawer.module.ts",
    "moduleName": "image-drawer.module.ts"
  }, {
    "name": "libs/drawers/task-drawer/task-drawer.module",
    "modulePath": "src/libs/drawers/task-drawer",
    "moduleFullPath": "src/libs/drawers/task-drawer/task-drawer.module.ts",
    "moduleName": "task-drawer.module.ts"
  }, {
    "name": "libs/duration-range/duration-range.module",
    "modulePath": "src/libs/duration-range",
    "moduleFullPath": "src/libs/duration-range/duration-range.module.ts",
    "moduleName": "duration-range.module.ts"
  }, {
    "name": "libs/estimate-min-max/estimate-min-max.module",
    "modulePath": "src/libs/estimate-min-max",
    "moduleFullPath": "src/libs/estimate-min-max/estimate-min-max.module.ts",
    "moduleName": "estimate-min-max.module.ts"
  }, {
    "name": "libs/file-attachments/file-attachments.module",
    "modulePath": "src/libs/file-attachments",
    "moduleFullPath": "src/libs/file-attachments/file-attachments.module.ts",
    "moduleName": "file-attachments.module.ts"
  }, {
    "name": "libs/global-search/global-search.module",
    "modulePath": "src/libs/global-search",
    "moduleFullPath": "src/libs/global-search/global-search.module.ts",
    "moduleName": "global-search.module.ts"
  }, {
    "name": "libs/highlight-related/highlight-related.module",
    "modulePath": "src/libs/highlight-related",
    "moduleFullPath": "src/libs/highlight-related/highlight-related.module.ts",
    "moduleName": "highlight-related.module.ts"
  }, {
    "name": "libs/highlighted-related-view/highlighted-related-view.module",
    "modulePath": "src/libs/highlighted-related-view",
    "moduleFullPath": "src/libs/highlighted-related-view/highlighted-related-view.module.ts",
    "moduleName": "highlighted-related-view.module.ts"
  }, {
    "name": "libs/invites-list/invites-list.module",
    "modulePath": "src/libs/invites-list",
    "moduleFullPath": "src/libs/invites-list/invites-list.module.ts",
    "moduleName": "invites-list.module.ts"
  }, {
    "name": "libs/last-modified/last-modified.module",
    "modulePath": "src/libs/last-modified",
    "moduleFullPath": "src/libs/last-modified/last-modified.module.ts",
    "moduleName": "last-modified.module.ts"
  }, {
    "name": "libs/layouts/card/card.module",
    "modulePath": "src/libs/layouts/card",
    "moduleFullPath": "src/libs/layouts/card/card.module.ts",
    "moduleName": "card.module.ts"
  }, {
    "name": "libs/layouts/side-nav/side-nav.module",
    "modulePath": "src/libs/layouts/side-nav",
    "moduleFullPath": "src/libs/layouts/side-nav/side-nav.module.ts",
    "moduleName": "side-nav.module.ts"
  }, {
    "name": "libs/logo/logo.module",
    "modulePath": "src/libs/logo",
    "moduleFullPath": "src/libs/logo/logo.module.ts",
    "moduleName": "logo.module.ts"
  }, {
    "name": "libs/material/material.module",
    "modulePath": "src/libs/material",
    "moduleFullPath": "src/libs/material/material.module.ts",
    "moduleName": "material.module.ts"
  }, {
    "name": "libs/name/name.module",
    "modulePath": "src/libs/name",
    "moduleFullPath": "src/libs/name/name.module.ts",
    "moduleName": "name.module.ts"
  }, {
    "name": "libs/not-found/not-found.module",
    "modulePath": "src/libs/not-found",
    "moduleFullPath": "src/libs/not-found/not-found.module.ts",
    "moduleName": "not-found.module.ts"
  }, {
    "name": "libs/object-icon/object-icon.module",
    "modulePath": "src/libs/object-icon",
    "moduleFullPath": "src/libs/object-icon/object-icon.module.ts",
    "moduleName": "object-icon.module.ts"
  }, {
    "name": "libs/object-identifier/object-identifier.module",
    "modulePath": "src/libs/object-identifier",
    "moduleFullPath": "src/libs/object-identifier/object-identifier.module.ts",
    "moduleName": "object-identifier.module.ts"
  }, {
    "name": "libs/object-versions/object-versions.module",
    "modulePath": "src/libs/object-versions",
    "moduleFullPath": "src/libs/object-versions/object-versions.module.ts",
    "moduleName": "object-versions.module.ts"
  }, {
    "name": "libs/or-line/or-line.module",
    "modulePath": "src/libs/or-line",
    "moduleFullPath": "src/libs/or-line/or-line.module.ts",
    "moduleName": "or-line.module.ts"
  }, {
    "name": "libs/pdf-manage/pdf-manage.module",
    "modulePath": "src/libs/pdf-manage",
    "moduleFullPath": "src/libs/pdf-manage/pdf-manage.module.ts",
    "moduleName": "pdf-manage.module.ts"
  }, {
    "name": "libs/pills/priority/priority-pill.module",
    "modulePath": "src/libs/pills/priority",
    "moduleFullPath": "src/libs/pills/priority/priority-pill.module.ts",
    "moduleName": "priority-pill.module.ts"
  }, {
    "name": "libs/pills/status/status-pill.module",
    "modulePath": "src/libs/pills/status",
    "moduleFullPath": "src/libs/pills/status/status-pill.module.ts",
    "moduleName": "status-pill.module.ts"
  }, {
    "name": "libs/pills/type/type-pill.module",
    "modulePath": "src/libs/pills/type",
    "moduleFullPath": "src/libs/pills/type/type-pill.module.ts",
    "moduleName": "type-pill.module.ts"
  }, {
    "name": "libs/pipes/key-name-value/key-name-value.module",
    "modulePath": "src/libs/pipes/key-name-value",
    "moduleFullPath": "src/libs/pipes/key-name-value/key-name-value.module.ts",
    "moduleName": "key-name-value.module.ts"
  }, {
    "name": "libs/project-create/project-create.module",
    "modulePath": "src/libs/project-create",
    "moduleFullPath": "src/libs/project-create/project-create.module.ts",
    "moduleName": "project-create.module.ts"
  }, {
    "name": "libs/project-image/project-image.module",
    "modulePath": "src/libs/project-image",
    "moduleFullPath": "src/libs/project-image/project-image.module.ts",
    "moduleName": "project-image.module.ts"
  }, {
    "name": "libs/project-roles/project-roles.module",
    "modulePath": "src/libs/project-roles",
    "moduleFullPath": "src/libs/project-roles/project-roles.module.ts",
    "moduleName": "project-roles.module.ts"
  }, {
    "name": "libs/related-objects/related-objects.module",
    "modulePath": "src/libs/related-objects",
    "moduleFullPath": "src/libs/related-objects/related-objects.module.ts",
    "moduleName": "related-objects.module.ts"
  }, {
    "name": "libs/rich-text/rich-text.module",
    "modulePath": "src/libs/rich-text",
    "moduleFullPath": "src/libs/rich-text/rich-text.module.ts",
    "moduleName": "rich-text.module.ts"
  }, {
    "name": "libs/search/search.module",
    "modulePath": "src/libs/search",
    "moduleFullPath": "src/libs/search/search.module.ts",
    "moduleName": "search.module.ts"
  }, {
    "name": "libs/social-button/social-button.module",
    "modulePath": "src/libs/social-button",
    "moduleFullPath": "src/libs/social-button/social-button.module.ts",
    "moduleName": "social-button.module.ts"
  }, {
    "name": "libs/status-groups/status-groups.module",
    "modulePath": "src/libs/status-groups",
    "moduleFullPath": "src/libs/status-groups/status-groups.module.ts",
    "moduleName": "status-groups.module.ts"
  }, {
    "name": "libs/status-manage/status-manage.module",
    "modulePath": "src/libs/status-manage",
    "moduleFullPath": "src/libs/status-manage/status-manage.module.ts",
    "moduleName": "status-manage.module.ts"
  }, {
    "name": "libs/status-menu/status-menu.module",
    "modulePath": "src/libs/status-menu",
    "moduleFullPath": "src/libs/status-menu/status-menu.module.ts",
    "moduleName": "status-menu.module.ts"
  }, {
    "name": "libs/subscribers/subscribers.module",
    "modulePath": "src/libs/subscribers",
    "moduleFullPath": "src/libs/subscribers/subscribers.module.ts",
    "moduleName": "subscribers.module.ts"
  }, {
    "name": "libs/task-create/task-create.module",
    "modulePath": "src/libs/task-create",
    "moduleFullPath": "src/libs/task-create/task-create.module.ts",
    "moduleName": "task-create.module.ts"
  }, {
    "name": "libs/task-type/task-type.module",
    "modulePath": "src/libs/task-type",
    "moduleFullPath": "src/libs/task-type/task-type.module.ts",
    "moduleName": "task-type.module.ts"
  }, {
    "name": "libs/tasks/tasks.module",
    "modulePath": "src/libs/tasks",
    "moduleFullPath": "src/libs/tasks/tasks.module.ts",
    "moduleName": "tasks.module.ts"
  }, {
    "name": "libs/time-entries/time-entries.module",
    "modulePath": "src/libs/time-entries",
    "moduleFullPath": "src/libs/time-entries/time-entries.module.ts",
    "moduleName": "time-entries.module.ts"
  }, {
    "name": "libs/timer/timer.module",
    "modulePath": "src/libs/timer",
    "moduleFullPath": "src/libs/timer/timer.module.ts",
    "moduleName": "timer.module.ts"
  }, {
    "name": "libs/type-menu/type-menu.module",
    "modulePath": "src/libs/type-menu",
    "moduleFullPath": "src/libs/type-menu/type-menu.module.ts",
    "moduleName": "type-menu.module.ts"
  }, {
    "name": "libs/types/types.module",
    "modulePath": "src/libs/types",
    "moduleFullPath": "src/libs/types/types.module.ts",
    "moduleName": "types.module.ts"
  }, {
    "name": "libs/upload-summary/upload-summary.module",
    "modulePath": "src/libs/upload-summary",
    "moduleFullPath": "src/libs/upload-summary/upload-summary.module.ts",
    "moduleName": "upload-summary.module.ts"
  }, {
    "name": "libs/workflow/workflow.module",
    "modulePath": "src/libs/workflow",
    "moduleFullPath": "src/libs/workflow/workflow.module.ts",
    "moduleName": "workflow.module.ts"
  }, {
    "name": "libs/workflows/workflows.module",
    "modulePath": "src/libs/workflows",
    "moduleFullPath": "src/libs/workflows/workflows.module.ts",
    "moduleName": "workflows.module.ts"
  }]
};
